# Site-wide settings
# ------------------
#
title: Vndmtrx
url: "https://vndmtrx.github.io"
lang: pt-BR

author:
  name: "Eduardo N. S. R."
  email: "vndmtrx@duck.com"
  tagline: "Vi Veri Vniversum Vivvs Vici"

#
# The `>` after `description:` means to ignore line-breaks until next key. If
#   you wish to omit the line-break after the end of text, use `>-` instead.
description: >
  Um blog com a proposta de falar sobre vários assuntos, desde desenvolvimento,
  passando por infra, devops, hacktivismo e até sobre conspirações alienígenas e
  portais circulares que permitem viagem a outros planetas.
  <br/><br/>Inclusive, se a criptografia fosse proibida, <em>fbzragr bf sbenf qn yrv grevnz cevinpvqnqr</em>...

# Build settings
# --------------
# Plugins
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-target-blank
 - jekyll-gfm-admonitions
 - jekyll-paginate-v2

gfm_admonitions:
  inject_css: false

sass:
  quiet_deps: true

kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]

pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: ':title - Página :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

autopages:
  enabled: true
  categories:
    layouts:
      - category.html
    title: ':cat'
    permalink: '/categorias/:cat/'
    slugify:
      mode: 'latin'
  collections:
    enabled: false
  tags:
    layouts:
      - tag.html
    title: ':tag'
    permalink: '/tags/:tag/'
    slugify:
      mode: 'latin'

# Configurações do tema (originalmente Minima)
minima:
  skin: auto
  nav_pages:
    - categorias.html
    - tutoriais.html
    - tags.html
    - about.md
  show_excerpts: true
  date_format: "%d/%m/%Y às %H:%M"
  social_links:
    - title: Github
      icon: github
      url: "https://github.com/vndmtrx"
    - title: Mastodon
      icon: mastodon
      url: "https://tech.lgbt/@vndmtrx"
    - title: Linkedin
      icon: linkedin
      url: "https://www.linkedin.com/in/eduardorolim/"
    - title: ORCID
      icon: orcid
      url: "https://orcid.org/0009-0006-5569-1816"
  hide_site_feed_link: false
