title: Vndmtrx
author:
  name: Eduardo N.S.R.
  email: vndmtrx@duck.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
#
description: >
  Um blog com a proposta de falar sobre vários assuntos, desde desenvolvimento,
  passando por infra, devops, hacktivismo e até sobre conspirações alienígenas e
  portais circulares que permitem viagem a outros planetas.

# Build settings
#
remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings
#
minima:
  skin: auto

  social_links:
    - { platform: github,         user_url: "https://github.com/vndmtrx" }
    - { platform: mastodon,       user_url: "https://bolha.us/@dudu" }


# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
  - about.md

# Set to `true` to show excerpts on the homepage.
#
show_excerpts: true