title: Vndmtrx
author: Eduardo N. S. R.

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
#
description: >
  Um blog com a proposta de falar sobre vários assuntos, desde desenvolvimento,
  passando por infra, devops, hacktivismo e até sobre conspirações alienígenas e
  portais circulares que permitem viagem a outros planetas.

# Build settings
#
remote_theme: daattali/beautiful-jekyll@6.0.1

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap

navbar-links:
  Sobre euzinhe: "about"

avatar: "/favicon-vetor.svg"
round-avatar: true

social-network-links:
  email: "vndmtrx@duck.com"
  rss: true
  github: "vndmtrx"
  mastodon: "tech.lgbt/@vndmtrx"
  ORCID: "0009-0006-5569-1816"
  linkedin: "eduardorolim"

share-links-active:
  twitter: false
  facebook: false
  linkedin: false
  vk: false
  reddit: false

url-pretty: "vndmtrx.github.io"
title-on-all-pages: true
excerpt_length: 50
feed_show_tags: true
date_format: "%B %-d, %Y"
timezone: "America/Sao_Paulo"
markdown: kramdown
highlighter: rouge
permalink: /posts/:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false  # add comments to all blog posts
      social-share: false # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"